CREATE TABLE users (
    id UUID PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    tipo_acesso VARCHAR(20) NOT NULL CHECK (tipo_acesso IN ('ORGANIZADOR', 'CLIENTE', 'PORTARIA')),
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
